/**
 * Represents state of spaceship at a given position, velocity and time.
 */
public final class SpaceshipState {
	private final int position;
	private final int velocity;
	private final int time;
	
	public SpaceshipState(final int position, final int velocity, final int time) {
		this.position = position;
		this.velocity = velocity;
		this.time = time;
	}
	/**
	 * Returns state generated by accelerating from this state
	 * @param acceleration 
	 * @return spaceship state after accelerating 
	 */
	public SpaceshipState accelerate(final int acceleration) {
		int newVelocity = velocity + acceleration;
		int newPosition = position + newVelocity;
		int newTime = time + 1;
		return new SpaceshipState(newPosition, newVelocity, newTime);
	}
	
	public int getPosition() {
		return position;
	}
	
	public int getVelocity() {
		return velocity;
	}
	
	public int getTime() {
		return time;
	}
	
	public boolean equals(Object obj) {
		if(!(obj instanceof SpaceshipState)) {
			return false;
		} else {
			SpaceshipState state = (SpaceshipState) obj;
			return (this.position == state.getPosition()) && (this.velocity == state.getVelocity())
					&& (this.time == state.getTime());
		}
	}
	
	public int hashCode(){
		return this.toString().hashCode();
	}
	
	public String toString() {
		return "(" + position + ", " + velocity + ", " + time + ")";		
	}
}